*** Testing printf() : error conditions ***

-- Testing printf() function with Zero arguments --
printf() expects at least 1 argument, 0 given

-- Testing printf() function with less than expected no. of arguments --

-- Call printf with one argument less than expected --
2 arguments are required, 1 given
3 arguments are required, 2 given
4 arguments are required, 3 given

-- Call printf with two argument less than expected --
3 arguments are required, 1 given
4 arguments are required, 2 given

-- Call printf with three argument less than expected --
4 arguments are required, 1 given